const roster=document.querySelector('#roster'),tpl=document.querySelector('#char-template'),results=document.querySelector('#results'),list=document.querySelector('#result-list'),toast=document.querySelector('#toast');
const synergy={비숍:12,은월:7,메르세데스:5,소울마스터:4};
const samples=[['쌀먹기사','아델',42,'1'],['우리집힐러','비숍',26,'1.08'],['극딜은나로','나이트로드',38,'0.9'],['달빛소마','소울마스터',31,'1'],['메르장인','메르세데스',36,'1.08']];
function flash(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function addChar(data=['','아델',35,'1']){const node=tpl.content.firstElementChild.cloneNode(true);node.querySelector('.nickname').value=data[0];node.querySelector('.job').value=data[1];node.querySelector('.power').value=data[2];node.querySelector('.skill').value=data[3];node.querySelector('.avatar').textContent=data[0]?.[0]||'?';node.querySelector('.nickname').addEventListener('input',e=>node.querySelector('.avatar').textContent=e.target.value[0]||'?');node.querySelector('.remove').onclick=()=>{if(roster.children.length<=2)return flash('후보는 최소 2명이 필요해요.');node.remove()};roster.append(node)}
samples.forEach(addChar);document.querySelector('#add').onclick=()=>addChar();document.querySelector('#reset').onclick=()=>results.classList.add('hidden');
function combinations(arr,k){const out=[];function pick(start,chosen){if(chosen.length===k){out.push([...chosen]);return}for(let i=start;i<=arr.length-(k-chosen.length);i++){chosen.push(arr[i]);pick(i+1,chosen);chosen.pop()}}pick(0,[]);return out}
document.querySelector('#recommend').onclick=()=>{const size=+document.querySelector('#size').value,boss=document.querySelector('#boss').value;const chars=[...roster.children].map((el,i)=>({name:el.querySelector('.nickname').value.trim()||`캐릭터 ${i+1}`,job:el.querySelector('.job').value,power:+el.querySelector('.power').value||0,skill:+el.querySelector('.skill').value}));if(chars.length<size)return flash('파티 인원보다 후보 캐릭터가 적어요.');const combos=combinations(chars,size).map(members=>{const raw=members.reduce((s,m)=>s+m.power*m.skill,0),buff=Math.min(18,members.reduce((s,m)=>s+(synergy[m.job]||0),0)),effective=raw*(1+buff/100),over=Math.abs(effective-108),variety=new Set(members.map(m=>m.job)).size,score=100-over+buff+variety;return{members,raw,effective,buff,score}}).sort((a,b)=>b.score-a.score).slice(0,3);list.innerHTML=combos.map((c,i)=>`<article class="result"><div class="result-top"><div class="rank"><strong>0${i+1}</strong> ${boss} 추천팟</div><div class="score"><b>${c.effective.toFixed(1)}%</b><span>예상 유효 기여도</span></div></div><div class="members">${c.members.map(m=>`<div class="member"><b>${escapeHtml(m.name)}</b><span>${m.job} · 입력 ${m.power}% · ${m.skill>1?'숙련':m.skill<1?'초행':'보통'}</span></div>`).join('')}</div><div class="reason">${c.effective>=100?'<i class="tag">목표 충족</i>':'<i class="tag">도전 조합</i>'}${c.buff?` 시너지 보정 +${c.buff}%를 반영했어요.`:' 순수 기여도를 중심으로 구성했어요.'} ${c.effective>130?'화력이 많이 남아 파티를 나눌 여지가 있어요.':c.effective<100?'클리어 안정성을 위해 후보를 보강하는 편이 좋아요.':'목표치에 가깝고 화력 낭비가 적은 조합이에요.'}</div></article>`).join('');results.classList.remove('hidden');results.scrollIntoView({behavior:'smooth',block:'start'});localStorage.setItem('boss-party-roster',JSON.stringify(chars))};
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
