const extra=document.createElement('style');extra.textContent=`nav{display:flex;gap:7px}.nav-btn{border:0;border-radius:10px;padding:9px 13px;background:transparent;color:#aeb2bd;font-weight:800}.nav-btn.active{background:#30333e;color:var(--acid)}.page{display:none}.page.active{display:block}.boss-list{display:grid;gap:9px}.boss-row{display:grid;grid-template-columns:1fr 82px 32px;gap:7px}.boss-row select{width:100%;border:1px solid #dfe2e8;border-radius:11px;padding:11px;background:#fff}.boss-remove{border:0;background:none;color:#9297a3;font-size:22px}.outline.full{width:100%;margin:10px 0 3px}.boss-rates{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(150px,1fr));gap:9px;border-top:1px dashed #d8dbe3;padding-top:12px}.boss-rates label>span{display:block;font-size:12px;font-weight:800;color:#555b69}.boss-tabs{display:flex;gap:8px;overflow-x:auto;margin-bottom:18px}.boss-tab{white-space:nowrap;border:1px solid #d8dbe3;border-radius:11px;padding:10px 14px;background:#fff;font-weight:850}.boss-tab.active{background:var(--ink);color:var(--acid)}.guide-hero{text-align:center;padding:28px 0 38px}.guide-hero h1{font-size:44px;margin:9px}.guide-hero>p:last-child{color:var(--muted)}.guide-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.guide-card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:28px}.guide-card.wide{grid-column:1/-1}.guide-num{color:var(--violet);font-weight:950;font-size:13px}.guide-card h2{font-size:25px;margin:8px 0}.guide-card>p{color:var(--muted);font-size:14px}.rule{display:grid;grid-template-columns:70px 70px 1fr;gap:10px;align-items:center;padding:15px 0;border-bottom:1px solid var(--line)}.rule strong,.synergy-table strong{color:var(--violet)}.rule small{color:var(--muted);line-height:1.5}.synergy-table{margin-top:18px;border-top:1px solid var(--line)}.synergy-table p{display:flex;justify-content:space-between;margin:0;padding:12px 3px;border-bottom:1px solid var(--line)}.model-note{display:block;margin-top:16px;background:#f4f2ff;color:#635a86;padding:13px;border-radius:12px;line-height:1.55}.principles{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.principles p{margin:8px 0;background:#f7f8fa;border-radius:15px;padding:18px}.principles b,.principles span{display:block}.principles span{font-size:13px;color:var(--muted);line-height:1.6;margin-top:8px}@media(max-width:820px){.guide-grid{grid-template-columns:1fr}.guide-card.wide{grid-column:auto}.principles{grid-template-columns:1fr}.boss-rates{grid-template-columns:1fr 1fr}}@media(max-width:480px){nav{gap:2px}.nav-btn{padding:8px}.boss-rates{grid-template-columns:1fr}.rule{grid-template-columns:60px 65px 1fr}.guide-card{padding:21px}}`;document.head.append(extra);
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],R=q('#roster'),B=q('#boss-list'),CT=q('#char-template'),BT=q('#boss-template'),OUT=q('#results'),LIST=q('#result-list'),TABS=q('#boss-tabs'),TOAST=q('#toast');
const SYN={비숍:12,은월:7,메르세데스:5,소울마스터:4};let cache={};
function flash(m){TOAST.textContent=m;TOAST.classList.add('show');setTimeout(()=>TOAST.classList.remove('show'),2200)}
function getBosses(){return[...B.children].map(x=>({name:x.querySelector('.boss-name').value,size:+x.querySelector('.boss-size').value}))}
function syncRates(){const bs=getBosses();[...R.children].forEach(c=>{const box=c.querySelector('.boss-rates'),old={};box.querySelectorAll('input').forEach(i=>old[i.dataset.boss]=i.value);box.innerHTML='';bs.forEach(b=>{const l=document.createElement('label');l.innerHTML='<span>'+b.name+' 보스 배율</span><div class="percent"><input type="number" min="0" max="300" value="'+(old[b.name]||35)+'" data-boss="'+b.name+'"><b>%</b></div>';box.append(l)})})}
function addBoss(name){const n=BT.content.firstElementChild.cloneNode(true);if(name)n.querySelector('.boss-name').value=name;n.querySelector('.boss-name').onchange=syncRates;n.querySelector('.boss-size').value=q('#default-size').value;n.querySelector('.boss-remove').onclick=()=>{if(B.children.length===1)return flash('보스는 한 개 이상 필요해요.');n.remove();syncRates()};B.append(n);syncRates()}
function addChar(d=['','', '아델','1']){const n=CT.content.firstElementChild.cloneNode(true);n.querySelector('.owner').value=d[0];n.querySelector('.nickname').value=d[1];n.querySelector('.job').value=d[2];n.querySelector('.skill').value=d[3];n.querySelector('.avatar').textContent=d[1]?.[0]||'?';n.querySelector('.nickname').oninput=e=>n.querySelector('.avatar').textContent=e.target.value[0]||'?';n.querySelector('.remove').onclick=()=>{if(R.children.length<=2)return flash('후보는 최소 2명이 필요해요.');n.remove()};R.append(n);syncRates()}
function combos(a,k){const o=[];(function f(s,c){if(c.length===k)return o.push([...c]);for(let i=s;i<=a.length-(k-c.length);i++){c.push(a[i]);f(i+1,c);c.pop()}})(0,[]);return o}
function readChars(){return[...R.children].map((c,i)=>({owner:c.querySelector('.owner').value.trim()||'소유자 '+(i+1),name:c.querySelector('.nickname').value.trim()||'캐릭터 '+(i+1),job:c.querySelector('.job').value,skill:+c.querySelector('.skill').value,rates:Object.fromEntries([...c.querySelectorAll('.boss-rates input')].map(x=>[x.dataset.boss,+x.value||0]))}))}
function showBoss(name){qa('.boss-tab').forEach(x=>x.classList.toggle('active',x.dataset.name===name));LIST.innerHTML='';(cache[name]||[]).slice(0,3).forEach((x,i)=>{const a=document.createElement('article');a.className='result';a.innerHTML='<div class="result-top"><div class="rank"><strong>0'+(i+1)+'</strong> 추천 조합</div><div class="score"><b>'+x.eff.toFixed(1)+'%</b><span>실전 예상 배율</span></div></div><div class="members">'+x.members.map(m=>'<div class="member"><b>'+m.name+'</b><span>'+m.owner+' · '+m.job+' · '+m.rates[name]+'%</span></div>').join('')+'</div><div class="reason"><i class="tag">소유자 중복 없음</i><i class="tag">시너지 +'+x.buff+'%</i> '+(x.eff>=100?'목표 배율을 충족해요.':'목표까지 '+(100-x.eff).toFixed(1)+'% 부족해요.')+'</div>';LIST.append(a)})}
q('#recommend').onclick=()=>{const chars=readChars();cache={};for(const b of getBosses()){cache[b.name]=combos(chars,b.size).filter(ms=>new Set(ms.map(m=>m.owner)).size===ms.length).map(ms=>{const raw=ms.reduce((s,m)=>s+m.rates[b.name]*m.skill,0),buff=Math.min(18,ms.reduce((s,m)=>s+(SYN[m.job]||0),0)),eff=raw*(1+buff/100);return{members:ms,buff,eff,score:100-Math.abs(eff-108)+buff}}).sort((a,b)=>b.score-a.score)}const names=Object.keys(cache);if(!names.length||!cache[names[0]].length)return flash('소유자가 겹치지 않는 조합이 부족해요.');TABS.innerHTML=names.map((n,i)=>'<button class="boss-tab '+(i?'':'active')+'" data-name="'+n+'">'+n+'</button>').join('');qa('.boss-tab').forEach(x=>x.onclick=()=>showBoss(x.dataset.name));OUT.classList.remove('hidden');showBoss(names[0]);OUT.scrollIntoView({behavior:'smooth'})};
q('#add').onclick=()=>addChar();q('#add-boss').onclick=()=>addBoss();q('#reset').onclick=()=>OUT.classList.add('hidden');qa('[data-page]').forEach(x=>x.onclick=()=>{qa('.page').forEach(p=>p.classList.remove('active'));q('#'+x.dataset.page+'-page').classList.add('active');qa('.nav-btn').forEach(n=>n.classList.toggle('active',n.dataset.page===x.dataset.page))});
addBoss('하드 세렌');addBoss('카오스 칼로스');[['철수','쌀먹기사','아델','1'],['영희','우리집힐러','비숍','1.08'],['민수','극딜은나로','나이트로드','.9'],['철수','달빛소마','소울마스터','1'],['지수','메르장인','메르세데스','1.08']].forEach(addChar);
